### ISSUE TITLE
ROS 2 migration

### ISSUE THREAD

**Issue by BarisYazici** [MarkFzp/mobile-aloha#1]
Is there any plan to adapt to the ROS 2?

**Comment by abhishek47kashyap** [comment]
I assume yes, because the readme states in section [Quick start guide](https://github.com/MarkFzp/mobile-aloha#quick-start-guide):

> Ongoing testing (compatibility effort underway):
>     🚧 ROS 2
>     🚧 >= Ubuntu 22.04

**Comment by BarisYazici** [comment]
cool right!
