### ISSUE TITLE
What is the core technology/principle for the autonomous skills? sim2real?

### ISSUE THREAD

**Issue by guotong1988** [MarkFzp/mobile-aloha#5]
I am new to this great project. Thank you very much!

**Comment by MarkFzp** [comment]
more details can be found at the project website: https://mobile-aloha.github.io/ 

thanks!

**Comment by guotong1988** [comment]
Thank you.

"We first present Mobile ALOHA, a low-cost and whole-body **teleoperation system for data collection**. It augments the ALOHA system with a mobile base, and a whole-body teleoperation interface. Using data collected with Mobile ALOHA, we then perform supervised **behavior cloning** and find that co-training with existing static ALOHA datasets boosts performance on mobile manipulation tasks."
